In [1]:
import sqlite3 as sql
import pandas as pd
import numpy as np
import re

seed = 101

Load the dataset from the previous notebook.

In [2]:
with sql.connect('../data/toxic.db') as conn:
    df = pd.read_sql_query('select * from toxic', conn)
df.head()

rev_id                                            comment  year  \
0   2232.0  This:\n:One can make an analogy in mathematica...  2002   
1   4216.0  "\n\n:Clarification for you  (and Zundark's ri...  2002   
2   8953.0                          Elected or Electoral? JHK  2002   
3  26547.0  "This is such a fun entry.   Devotchka\n\nI on...  2002   
4  28959.0  Please relate the ozone hole to increases in c...  2002   

   logged_in       ns  sample  split  min  max  avg  y  
0          1  article  random  train -1.0  1.0  0.4  0  
1          1     user  random  train  0.0  2.0  0.5  0  
2          0  article  random   test  0.0  1.0  0.1  0  
3          1  article  random  train  0.0  2.0  0.6  0  
4          1  article  random   test -1.0  1.0  0.2  0

Remember to isolate the train, dev, and test sets.

In [3]:
idx_train = df['split'] == 'train'
idx_dev = df['split'] == 'dev'
idx_test = df['split'] == 'test'

Let's start things off with a pretty basic model to serve as a baseline: a CountVectorizer and a LogisticRegression. We'll start with the tokenizer we developed in the exploration step.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import SGDClassifier

def tokenizer(text):
    return re.findall(r'[a-z0-9]+', text.lower())

vect = CountVectorizer(tokenizer=tokenizer)
clf = SGDClassifier(loss='log', max_iter=100, tol=1e-6, random_state=seed)

In [5]:
X_train = df.loc[idx_train, 'comment'].values
X_dev = df.loc[idx_dev, 'comment'].values

y_train = df.loc[idx_train, 'y'].values
y_dev = df.loc[idx_dev, 'y'].values

X_train_vect = vect.fit_transform(X_train)
X_dev_vect = vect.transform(X_dev)

In [6]:
clf.fit(X_train_vect, y_train)
y_pred = clf.predict(X_dev_vect)
np.mean(y_dev==y_pred)

0.8941110557768924

Nice, we nearly got 90% on the dev set. Is accuracy a good metric for this problem though?

In [7]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_dev, y_pred)

array([[25625,   625],
       [ 2777,  3101]], dtype=int64)

In [8]:
from sklearn.metrics import classification_report

print(classification_report(y_dev, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     26250
           1       0.83      0.53      0.65      5878

   micro avg       0.89      0.89      0.89     32128
   macro avg       0.87      0.75      0.79     32128
weighted avg       0.89      0.89      0.88     32128



The recall is pretty poor for the positive class. Let's take a look at a situation where we incorrectly classified a comment.

In [9]:
idx_error = (y_dev != y_pred) & (y_dev == 1)
print(X_dev[idx_error][1])

Removed from article: 
:An extra-large common pork sausage was named after him.  

Nah.  


That's strange, what was the average toxicity score for this instance?

In [10]:
df['hash'] = df['comment'].map(hash)
df[df['hash'] == hash(X_dev[idx_error][1])]

rev_id                                            comment  year  \
445  2943468.0  Removed from article: \n:An extra-large common...  2003   

     logged_in       ns  sample split  min  max  avg  y                 hash  
445          1  article  random   dev -1.0  1.0 -0.1  1 -5817327908936797672

This may indicate problems in the dataset (or how we aggregate the scores). At this point, I would normally revisit the EDA step to review the labeling function, but let's forge ahead for now. Since we have a pretty large imbalance and the positive class is low, let's use F1 as the evaluation metric.

In [11]:
from sklearn.metrics import f1_score

f1_score(y_dev, y_pred)

0.6457725947521866

So how do we efficiently tune our hyperparameters? We can use GridSearchCV or RandomizedSearchCV, but we have a pre-defined dev set so we need to use some tricks to override the normal behavior. This is actually pretty standard for large-scale NLP problems. Cross-validation is preferred, but often not feasible for large datasets.

```
For some datasets, a pre-defined split of the data into training- and validation fold or into several cross-validation folds already exists. Using PredefinedSplit it is possible to use these folds e.g. when searching for hyperparameters.

For example, when using a validation set, set the test_fold to 0 for all samples that are part of the validation set, and to -1 for all other samples.
```

In [12]:
from sklearn.model_selection import PredefinedSplit, GridSearchCV
from sklearn.pipeline import Pipeline

df_train_dev = df[df['split'].map(lambda x: x in {'train', 'dev'})].copy()
idx = np.where(df_train_dev['split'] == 'dev', 0, -1) # See documentation above

ps = PredefinedSplit(idx)

In [13]:
ps.get_n_splits()

1

In [14]:
pipe = Pipeline([('vect', CountVectorizer(tokenizer=tokenizer)),
                 ('clf', SGDClassifier(loss='log', max_iter=10, tol=1e-6, penalty='elasticnet', random_state=seed))])
param_grid = {'vect__ngram_range':[(1,1), (1,2)], 'vect__min_df':[1, 2, 5, 10, 20],
              'clf__l1_ratio':[0.0, 0.1, 0.2], 'clf__class_weight':[{0:1,1:1}, {0:1,1:2}]}
gs = GridSearchCV(pipe, param_grid, scoring='f1', n_jobs=6, cv=ps, verbose=2)
gs.fit(df_train_dev['comment'].values, df_train_dev['y'].values)
print(gs.best_params_)
print(gs.best_score_)

Fitting 1 folds for each of 60 candidates, totalling 60 fits


[Parallel(n_jobs=6)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=6)]: Done  29 tasks      | elapsed:  3.1min
[Parallel(n_jobs=6)]: Done  60 out of  60 | elapsed:  6.4min finished


{'clf__class_weight': {0: 1, 1: 2}, 'clf__l1_ratio': 0.0, 'vect__min_df': 1, 'vect__ngram_range': (1, 2)}
0.7008292182987049


C:\Users\jking\AppData\Local\Continuum\Anaconda3\envs\nlp\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:603: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


Since this step took so long, I am going to persist the result sto disk using joblib (cooking-show style).

In [15]:
from sklearn.externals.joblib import dump, load

dump(gs, '../results/gs_cv_sgd.joblib')

['../results/gs_cv_sgd.joblib']

Now let's look at the results.

In [16]:
y_pred = gs.best_estimator_.predict(X_dev)
confusion_matrix(y_dev, y_pred)

array([[25748,   502],
       [  588,  5290]], dtype=int64)

In [17]:
print(classification_report(y_dev, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98     26250
           1       0.91      0.90      0.91      5878

   micro avg       0.97      0.97      0.97     32128
   macro avg       0.95      0.94      0.94     32128
weighted avg       0.97      0.97      0.97     32128



In [18]:
np.mean(y_dev==y_pred)

0.9660732071713147

Not a bad result! Let's see if adding a TfidfTransformer can make a difference. Remember, TFIDF will reduce the impact of high-frequency words and increase the impact of rare words.

In [19]:
from sklearn.feature_extraction.text import TfidfTransformer

pipe = Pipeline([('vect', CountVectorizer(tokenizer=tokenizer)),
                 ('tfidf', TfidfTransformer()),
                 ('clf', SGDClassifier(loss='log', max_iter=10, tol=1e-6, penalty='elasticnet', n_jobs=2))])
param_grid = {'vect__ngram_range':[(1,1), (1,2)], 'vect__min_df':[1, 2, 5, 10, 20],
              'clf__l1_ratio':[0.0, 0.1, 0.2], 'clf__class_weight':[{0:1,1:1}, {0:1,1:2}]}
gs = GridSearchCV(pipe, param_grid, scoring='f1', n_jobs=4, cv=ps, verbose=2)
gs.fit(df_train_dev['comment'].values, df_train_dev['y'].values)
print(gs.best_params_)
print(gs.best_score_)

Fitting 1 folds for each of 60 candidates, totalling 60 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:  4.4min
[Parallel(n_jobs=4)]: Done  60 out of  60 | elapsed:  8.2min finished


{'clf__class_weight': {0: 1, 1: 2}, 'clf__l1_ratio': 0.0, 'vect__min_df': 20, 'vect__ngram_range': (1, 1)}
0.6760426770126091


Again, let's store the result.

In [20]:
dump(gs, '../results/gs_cv_tfidf_sgd.joblib')

['../results/gs_cv_tfidf_sgd.joblib']

In [21]:
X_dev = df.loc[idx_dev, 'comment'].values
y_dev = df.loc[idx_dev, 'y'].values

y_pred = gs.best_estimator_.predict(X_dev)
confusion_matrix(y_dev, y_pred)

array([[25403,   847],
       [ 2368,  3510]], dtype=int64)

In [22]:
print(classification_report(y_dev, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94     26250
           1       0.81      0.60      0.69      5878

   micro avg       0.90      0.90      0.90     32128
   macro avg       0.86      0.78      0.81     32128
weighted avg       0.89      0.90      0.89     32128



In [23]:
np.mean(y_dev==y_pred)

0.8999315239043825